server:
  port: 8086

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8084/eureka

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/abhijeetroshan/microservice-configuration
          clone-on-start: true
          default-label: main
  application:
    name: CONFIG-SERVER